# Generated by Django 3.0.2 on 2020-01-11 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'OEMs',
            },
        ),
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('oem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swengs_hw_app.OEM')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('coremultiplier', models.CharField(choices=[('u', 'Unlocked'), ('l', 'Locked')], max_length=1)),
                ('release_date', models.DateField()),
                ('price', models.PositiveIntegerField(help_text='in Euros')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swengs_hw_app.OEM')),
                ('memorySupport', models.ManyToManyField(blank=True, to='swengs_hw_app.MemoryType')),
            ],
            options={
                'verbose_name_plural': 'CPUs',
            },
        ),
    ]
