# Generated by Django 3.0.2 on 2020-01-11 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swengs_hw_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oem',
            name='ceo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oem',
            name='dateOfFounding',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='oem',
            name='employeeCount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oem',
            name='stockIndexName',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
